//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account inactive..
        /// </summary>
        internal static string ErrorAccountInactive {
            get {
                return ResourceManager.GetString("ErrorAccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed..
        /// </summary>
        internal static string ErrorConnectionFailed {
            get {
                return ResourceManager.GetString("ErrorConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Existed..
        /// </summary>
        internal static string ErrorDataExisted {
            get {
                return ResourceManager.GetString("ErrorDataExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Found..
        /// </summary>
        internal static string ErrorDataNotFound {
            get {
                return ResourceManager.GetString("ErrorDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed..
        /// </summary>
        internal static string ErrorFailed {
            get {
                return ResourceManager.GetString("ErrorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data mis-match..
        /// </summary>
        internal static string ErrorInputDataMisMatch {
            get {
                return ResourceManager.GetString("ErrorInputDataMisMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access..
        /// </summary>
        internal static string ErrorInvalidAccess {
            get {
                return ResourceManager.GetString("ErrorInvalidAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha.
        /// </summary>
        internal static string ErrorInvalidCaptcha {
            get {
                return ResourceManager.GetString("ErrorInvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credential.
        /// </summary>
        internal static string ErrorInvalidCredential {
            get {
                return ResourceManager.GetString("ErrorInvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        internal static string ErrorInvalidData {
            get {
                return ResourceManager.GetString("ErrorInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hashing..
        /// </summary>
        internal static string ErrorInvalidHashing {
            get {
                return ResourceManager.GetString("ErrorInvalidHashing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        internal static string ErrorInvalidInput {
            get {
                return ResourceManager.GetString("ErrorInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input Format.
        /// </summary>
        internal static string ErrorInvalidInputFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidInputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        internal static string ErrorInvalidRequest {
            get {
                return ResourceManager.GetString("ErrorInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid timestamp..
        /// </summary>
        internal static string ErrorInvalidTimestamp {
            get {
                return ResourceManager.GetString("ErrorInvalidTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request not responding.
        /// </summary>
        internal static string ErrorNotResponding {
            get {
                return ResourceManager.GetString("ErrorNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required param not supplied..
        /// </summary>
        internal static string ErrorParameterNotSupplied {
            get {
                return ResourceManager.GetString("ErrorParameterNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server under maintenance.
        /// </summary>
        internal static string ErrorServerMaintnance {
            get {
                return ResourceManager.GetString("ErrorServerMaintnance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not responding..
        /// </summary>
        internal static string ErrorServerNotRespondence {
            get {
                return ResourceManager.GetString("ErrorServerNotRespondence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timeout..
        /// </summary>
        internal static string ErrorSessionTimeout {
            get {
                return ResourceManager.GetString("ErrorSessionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string ErrorSuccess {
            get {
                return ResourceManager.GetString("ErrorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error..
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string LblActive {
            get {
                return ResourceManager.GetString("LblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Select-.
        /// </summary>
        internal static string LblDefaultSelectDDL {
            get {
                return ResourceManager.GetString("LblDefaultSelectDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LblError {
            get {
                return ResourceManager.GetString("LblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill to Search.
        /// </summary>
        internal static string LblFillToSearch {
            get {
                return ResourceManager.GetString("LblFillToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        internal static string LblGridViewEntries {
            get {
                return ResourceManager.GetString("LblGridViewEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        internal static string LblGridViewNoData {
            get {
                return ResourceManager.GetString("LblGridViewNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string LblGridViewSearch {
            get {
                return ResourceManager.GetString("LblGridViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string LblGridViewShow {
            get {
                return ResourceManager.GetString("LblGridViewShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string LblInactive {
            get {
                return ResourceManager.GetString("LblInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading more.
        /// </summary>
        internal static string LblLoadMore {
            get {
                return ResourceManager.GetString("LblLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max select 10 items.
        /// </summary>
        internal static string LblMaximumSelectNote {
            get {
                return ResourceManager.GetString("LblMaximumSelectNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input at least {0} characters.
        /// </summary>
        internal static string LblNotLessThanChar {
            get {
                return ResourceManager.GetString("LblNotLessThanChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input not more than.
        /// </summary>
        internal static string LblNotMoreThanChar {
            get {
                return ResourceManager.GetString("LblNotMoreThanChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YABAM.
        /// </summary>
        internal static string LblPageTitle {
            get {
                return ResourceManager.GetString("LblPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string LblPleaseWait {
            get {
                return ResourceManager.GetString("LblPleaseWait", resourceCulture);
            }
        }
    }
}
